- name: install tomcat as services
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    mode: "0644"
  become: yes
  become_method: sudo

- name: demaon reload
  systemd:
    daemon_reload: yes
  become: yes
  notify:
    - tomcat
    