---
tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.74/bin/apache-tomcat-9.0.74.tar.gz
tomcat_download_dir: apache-tomcat-9.0.74
tomcat_install_dir: /u01/middleware
jdk_pgk: openjdk-11-jdk
tomcat_os_user: tomcat
tomcat_os_group: tomcat
...
